topo:
  agent_addr: "localhost:9992"
  datasource: "gopsutil"
PilotGo:
  http_addr: "localhost:8887"
log:
  level: debug
  driver: stdout    
  path: /var/log/topo.log
  max_file: 1
  max_size: 10485760