topo:
  server_addr: "192.168.75.100:9991"
  agent_port: "9992"
  period: 60
PilotGo:
  http_addr: "192.168.75.100:8887"
log:
  level: debug
  driver: stdout    
  path: /var/log/topo.log
  max_file: 1
  max_size: 10485760
arangodb:
  addr: "http://localhost:8529"
  database: "pilotgo-topo"