#!/bin/bash


SERVERMAIN="/home/wjq/a-disk/PilotGo-plugins/topology/server/main.go"
SERVERSCRIPT="/home/wjq/a-disk/PilotGo-plugins/topology/toposerver"
AGENTMAIN="/home/wjq/a-disk/PilotGo-plugins/topology/agent/main.go"
AGENTSCRIPT="/home/wjq/a-disk/PilotGo-plugins/topology/topoagent"
AGENTREMOTE="/opt/topo"

echo -e "\e[32m build server \e[0m"
go build -o $SERVERSCRIPT ${SERVERMAIN}
echo -e "\e[32m build agent \e[0m"
go build -o $AGENTSCRIPT $AGENTMAIN

case "x$#" in
        x1) 
                echo -e "\e[32m upload to $1 \e[0m"
                scp $AGENTSCRIPT root@192.168.75.$1:$AGENTREMOTE > /dev/null
                ;;  
        x2) 
                echo -e "\e[32m upload to $1 \e[0m"
                scp $AGENTSCRIPT root@192.168.75.$1:$AGENTREMOTE > /dev/null
                echo -e "\e[32m upload to $2 \e[0m"
                scp $AGENTSCRIPT root@192.168.75.$2:$AGENTREMOTE > /dev/null
                ;;  
        x3) 
                echo -e "\e[32m upload to $1 \e[0m"
                scp $AGENTSCRIPT root@192.168.75.$1:$AGENTREMOTE > /dev/null
                echo -e "\e[32m upload to $2 \e[0m"
                scp $AGENTSCRIPT root@192.168.75.$2:$AGENTREMOTE > /dev/null
                echo -e "\e[32m upload to $3 \e[0m"
                scp $AGENTSCRIPT root@192.168.75.$3:$AGENTREMOTE > /dev/null
                ;;
esac
