http_server:
    addr: localhost:8288
log:
    level: debug
    # 可选stdout和file.stdout:输出到终端控制台;file:输出到path下的指定文件。
    driver: stdout
    path: ./log/plugin_automation.log
    max_file: 1
    max_size: 10485760
mysql:
    host: localhost
    port: 3306
    user: root
    password: Qwer!234578
    database: PluginAutomation
redis:
    # 分为单机模式和哨兵模式, 可选值: standalone和sentinel
    deploy_mode: standalone
    host: 127.0.0.1:6379
    sentinel_hosts: 1.1.1.1:26379,1.1.1.2:26379,1.1.1.3:26379
    master_name: mymaster
    password: Qwer!234578
    default_db: 0
    dial_timeout: 5s
    enable_redis: true
    use_tls: false
etcd:
    endpoints:
        - localhost:2379
    service_name: automation-service
    version: "3.0"
    dialTimeout: 5s
    menu_name: 智能运维调度中心
    icon: el-icon-setting
