http_server:
    addr: localhost:8288
log:
    level: debug
    # 可选stdout和file.stdout:输出到终端控制台;file:输出到path下的指定文件。
    driver: file
    path: ./log/plugin_automation.log
    max_file: 1
    max_size: 10485760
mysql:
    host: localhost
    port: 3306
    user: root
    password: Qwer!234578
    database: PluginAutomation
etcd:
    endpoints:
        - localhost:2379
    service_name: automation-service
    version: "3.0"
    dialTimeout: 5s
    menu_name: 智能运维调度中心
    icon: el-icon-setting
